// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PasswordController from "./password_controller"
application.register("password", PasswordController)

import RecordFormController from "./record_form_controller"
application.register("record-form", RecordFormController)

import ReportController from "./report_controller"
application.register("report", ReportController)

import SubjectsController from "./subjects_controller"
application.register("subjects", SubjectsController)
