// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SubjectsController from "./subjects_controller"
application.register("subjects", SubjectsController)

import ReportController from "./report_controller"
application.register("report", ReportController)

import GradeFormController from "./grade-form-controller"
application.register("grade-form", GradeFormController)