version: '3.8' 
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db_network

  web:
    build: .
    command: >
      bash -c "bin/rails db:create db:migrate db:seed && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  pgdata: