default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: 5

development:
  <<: *default
  database: electronic_grade_book_development
  username: postgres
  password: password

test:
  <<: *default
  database: electronic_grade_book_test
  username: postgres
  password: password

production:
  <<: *default
  database: electronic_grade_book_production
  username: electronic_grade_book
  password: <%= ENV["ELECTRONIC_GRADE_BOOK_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
  