default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: electronic_grade_book_development

test:
  <<: *default
  database: electronic_grade_book_test

production:
  <<: *default
  database: electronic_grade_book_production
  username: electronic_grade_book
  password: <%= ENV["ELECTRONIC_GRADE_BOOK_DATABASE_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>
